### ISSUE TITLE
Keyerror: 'sgns'

### ISSUE THREAD

**Issue by ogarciasierra** [TimotheeMickus/codwoe#1]
Good morning. 

While trying to score my revdict predictions I'm facing this issue:

![problem](https://user-images.githubusercontent.com/81616720/151316174-a8ff02ef-7595-4495-b617-57f1be9ed937.png)

This doen's make much sense, since the checker didn't find any issue with my predictions format. 

Any idea which could be the problem?

**Comment by TimotheeMickus** [comment]
Hi!

It seems that one of your predictions did not contain the SGNS target vector. The target vectors are computed by looking up the first item only (cf. [here](https://github.com/TimotheeMickus/codwoe/blob/main/code/check_output.py#L68))
It might be easier for me to debug your problem if you send me the submissions through the discord server.

**Comment by ogarciasierra** [comment]
I am sending them right now.

**Comment by TimotheeMickus** [comment]
For any future reader, the issue stemmed from using the input test dataset as reference data, hence the SGNS keys were missing from the reference.  

During the evaluation phase, inputs should be submitted on the codalab website; the reference data will be made available at the end of the evaluation phase.
